name: Build
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  Windows:
    name: Windows (VS2022)
    runs-on: windows-latest
    env:
      VS_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-2.30.5/SDL2-devel-2.30.5-VC.zip" -OutFile "SDL2-devel-2.30.5-VC.zip"
          Expand-Archive -Path SDL2-devel-2.30.5-VC.zip
          echo "SDL2_DIR=$(pwd)\SDL2-devel-2.30.5-VC\SDL2-2.30.5\" >>${env:GITHUB_ENV}

      - name: Build-Debug
        shell: cmd
        run: |
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build-debug
          cd build-debug
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
          nmake

      - name: Build-Release
        shell: cmd
        run: |
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          mkdir build-release
          cd build-release
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
          nmake

  Linux:
    name: Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake ninja-build libsdl2-dev libdbus-1-dev

      - name: Build-Debug
        run: |
          mkdir build-debug
          cd build-debug
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
          ninja

      - name: Build-Release
        run: |
          mkdir build-release
          cd build-release
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja
