name: Linux
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  Build:
    name: Linux (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake ninja-build libsdl2-dev libdbus-1-dev

      - name: Build-Debug
        run: |
          mkdir build-debug
          cd build-debug
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..
          ninja

      - name: Build-Release
        run: |
          mkdir build-release
          cd build-release
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          ninja
